#User settings
#Mon Sep 07 02:08:21 BST 2026
calendar_numbers=off
daily_fat_update=on
daily_muscle_update=on
daily_weight_update=on
photos_panel=on
return_on_completion=on
return_on_fail=off
theme=light mode
